# Login Credentials
admin.email=super_admin@gmail.com
admin.password=R1mep@321

# Application URL
base.url=https://dev.we1.co/#/login
# Browser Settings
browser=chrome
headless=false

# Wait Timeouts
implicit.wait=10
explicit.wait=30

filter.name=TC_CA_
#excel.name=Book1.csv
#excel.name=Book1.csv
excel.name=testingwe13.xlsx
#excel.name=run_sequential.csv
sheets.name=CityArea,CityAdmin,AddAutoDriver,AddBikeDriver