# Login Credentials
admin.email=super_admin@gmail.com
admin.password=R1mep@321

# Application URL
base.url=https://dev.we1.co/#/login
dashboard.url=https://dev.we1.co/#/page-module/dashboard_dynamic
# Browser Settings
browser=chrome
headless=false

# Wait Timeouts
implicit.wait=10
explicit.wait=30

filter.name=TC_CA_
#excel.name=Book1.csv
#excel.name=Book1.csv
excel.name=we1_superAdmin_regression.xlsx
#excel.name=run_sequential.csv
sheets.name=SuperAdminLogin,AddCustomer,AddCityArea,AddCityAdmin,AddAutoDriver,AddBikeDriver,AddTaxiDriver,TransportServiceCompleteTest,AddStore,StoreOperations,StoreStatusManagement,DeliveryServiceCompleteTest,AddProvider,ProviderServiceCompleteTest,DataCleanUpSheet